AllCops:
  TargetRubyVersion: 3.0

plugins:
  - rubocop-rake
  - rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
